agrego Loader para que no se generen multiples peticiones
jonathanParamo/storageAdministration pull request #4
Opened 2022-06-02 00:22 UTC by jonathanParamo

2022-06-04 02:03 UTC, Pethofreed requested changes

2022-06-04 02:03 UTC, Pethofreed commented on .env
> +SERVER=https://safe-reef-90017.herokuapp.com
No subir este archivo...preferiblemente eliminarlo.

2022-06-04 02:03 UTC, Pethofreed commented on src/components/Loader/index.jsx
> +const Loader = () => <div class="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
Muy larga y fea esta linea...
Poner multilinea mejor e identar.

2022-06-04 02:03 UTC, Pethofreed commented on src/components/Loader/index.jsx
> +const Loader = () => <div class="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
![image](https://user-images.githubusercontent.com/72000838/171970988-6358a62a-8a11-4513-a486-b046679b6d30.png)

2022-06-04 02:03 UTC, Pethofreed commented on src/components/Loader/styles.css
> +}
De acá el width lo baja a 77px, agrega un  margin: 25px 0; y el resto lo elimina (color, display, position, height).

2022-06-04 02:03 UTC, Pethofreed commented on src/components/Loader/styles.css
> +  transform-origin: 40px 40px;
eliminar el transform origin...

2022-06-04 02:03 UTC, Pethofreed commented on src/components/Loader/styles.css
> +}
De acá, puede eliminar el espacio en blanco dentro de las comillas de la linea 13.
Eliminar display...
top: 5px;
width: 3px; 
height: 8px;

El largor de los palitos es el height. por si los quiere poner mas largos.
El tamaño de la ruedita la cambia con width...que en este caso con 3px está bien.

2022-06-04 02:03 UTC, Pethofreed commented on src/components/Loader/styles.css
> +}
Pero si quiere cambiar esos tamaños, tambien debe probar cambiando el width de la linea 5, porque le van a quedar torcidos...

2022-06-04 02:03 UTC, Pethofreed commented on src/components/Signin/index.jsx
> +  }, [email, password], signUpError)
Esto está mal....el signUpIndex, debe ir entre el array de dependencias, no afuera.

2022-06-04 02:03 UTC, Pethofreed commented on src/components/Signup/index.jsx
> +          <p>You have an account? enter</p>
Enter => Mayuscula

2022-06-04 02:03 UTC, Pethofreed commented on src/components/Signup/index.jsx
> +        baseURL: process.env.SERVER,
Esto no va a funcionar, no porque esté malo, sinó porque para que funcionen las variables de entorno, debe instalar la libreria dotenv
yarn add dotenv, por eso le sale el error...
La peticion no la está tirando al servidor sino al localhost:300

2022-06-04 02:03 UTC, Pethofreed commented on src/components/Signup/index.jsx
> +        baseURL: process.env.SERVER,
![image](https://user-images.githubusercontent.com/72000838/171972364-47988b49-56b4-4d55-9693-b195b2564dcc.png)

2022-06-04 02:03 UTC, Pethofreed commented on src/components/Signup/index.jsx
> +      localStorage.setItem("token", data)
hay que hacer log de data para saber como llega el token...no estoy seguro que sea solo data.
de pronto es data.token o algo así..

2022-06-04 22:54 UTC, jonathanParamo commented on .env
> +SERVER=https://safe-reef-90017.herokuapp.com
este paso no estoy seguro de como hacerlo. pero ya agg, el archivo .env al .gitignore

2022-06-04 23:10 UTC, Pethofreed requested changes

2022-06-04 23:10 UTC, Pethofreed commented on src/components/Loader/styles.css
> +  content: " ";
acá si quiere puede eliminar este espacio en blanco del " "

2022-06-04 23:10 UTC, Pethofreed commented on src/components/Signup/index.jsx
> +  const [loading, setLoading] = useState(true)
loading no puede empezar en => true, porque sino siempre se va a mostrar el loader.

2022-06-04 23:10 UTC, Pethofreed commented on src/components/Signup/index.jsx
> +      console.log(data.token);
el console.log es para ud en local... para que mire cómo llega la data, no para subirlo al codigo. Eliminar please.

2022-06-07 01:03 UTC, Pethofreed commented on .env
> +SERVER=https://safe-reef-90017.herokuapp.com
Ya se porqué tiene el problema que no le reconoce la variable de entorno...
Debe ponerle al nombre antes esto => REACT_APP_NOMBREDEVARIABLE.

Ejemplo => REACT_APP_SERVER=talytal

2022-06-09 13:44 UTC, Pethofreed commented on src/components/Signup/index.jsx
> +      console.log(data.token);
Eliminar el console.log, el token no debe quemarse por consola.

2022-06-09 21:17 UTC, Pethofreed approved these changes

2022-06-09 22:12 UTC, merged