creo el componente MainMenu y modifico estilos del LogOut
jonathanParamo/storageAdministration pull request #7
Opened 2022-06-21 22:40 UTC by jonathanParamo

2022-06-22 22:02 UTC, Pethofreed requested changes
Creo que en lugar de manejar la verificación por token desde los componentes, podria manejarse desde la barra de navegación, puesto que esa barra va a estar siempre en todo lado.

2022-06-22 22:04 UTC, Pethofreed commented
En ese orden de ideas, se podría quitar lo que hicimos en el useEffect de "Home" y pasarlo al nuevo componente "MainMenu".

Pregunta ¿MainMenu y La barra de navegación van a ser dos cosas diferentes o son lo mismo?

2022-06-22 22:38 UTC, jonathanParamo commented
> 

si planeo, crear diferentes componentes y agruparlos en Home, no se, ¿sera una buena practica o que me recomienda?

2022-06-23 02:40 UTC, Pethofreed requested changes

2022-06-23 02:40 UTC, Pethofreed commented on src/components/MainMenu/index.jsx
> +  </div>
Todo este código, desde la linea 16 hasta la 47 le falta una identación.
Cuidado, ojo con las identaciones.

2022-06-23 02:40 UTC, Pethofreed commented on src/components/Signin/index.jsx
>                name="signUp"
¿cual es este button? porque tiene className => SignInButton y tiene como name "signUp"

2022-06-23 04:20 UTC, jonathanParamo commented on src/components/Signin/index.jsx
>                name="signUp"
error mio es signIn

2022-06-23 22:52 UTC, Pethofreed approved these changes

2022-06-24 04:52 UTC, merged